FROM rust as build

COPY . /app

WORKDIR /app

RUN cargo build --release

FROM gcr.io/distroless/cc-debian12

COPY --from=build /app/target/release/docker-rust /app/docker-rust

WORKDIR /app

CMD ["./docker-rust"]